server:
  port: 8051

spring:
  datasource:
    url: "jdbc:mysql://129.204.64.4:3306/msg"
    username: "root"
    password: "ccx.123456"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-wait: 10000
      max-active: 10
      initial-size: 8
      min-idle: 5
      query-timeout: 10000
      transaction-query-timeout: 30000
      remove-abandoned-timeout: 30000
  redis:
    host: 129.204.64.4
    port: 6379
    password:
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10

# redis 缓存配置 , key值的失效时间
cache:
  config:
    # key: 时间 ，d天， h小时 m分钟 s秒 毫秒ms 微秒us 纳秒ns
    name: 10m
    name2: 1000s
  def-time: 1d

mybatis:
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml

gateway:
  # 白名单设置
  allow:
    - /test/push
    - /test/get

